// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 63.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class AppAssets {
  static const String package = 'movie';

  static const String dev_env = '.env/dev.env';

  static const String prod_env = '.env/prod.env';

  static const String countries_json = 'assets/country/countries.json';

  static const String apple_svg = 'assets/icons/apple.svg';

  static const String facebook_svg = 'assets/icons/facebook.svg';

  static const String google_svg = 'assets/icons/google.svg';

  static const String ic__premium_svg = 'assets/icons/ic_ premium.svg';

  static const String ic_apple_pay_svg = 'assets/icons/ic_apple_pay.svg';

  static const String ic_arrow_dropdown_svg = 'assets/icons/ic_arrow_dropdown.svg';

  static const String ic_arrow_right_svg = 'assets/icons/ic_arrow_right.svg';

  static const String ic_auto_svg = 'assets/icons/ic_auto.svg';

  static const String ic_calendar_svg = 'assets/icons/ic_calendar.svg';

  static const String ic_card_account_png = 'assets/icons/ic_card_account.png';

  static const String ic_checked_svg = 'assets/icons/ic_checked.svg';

  static const String ic_congratulation_svg = 'assets/icons/ic_congratulation.svg';

  static const String ic_dark_mode_svg = 'assets/icons/ic_dark_mode.svg';

  static const String ic_divider_svg = 'assets/icons/ic_divider.svg';

  static const String ic_dowload_svg = 'assets/icons/ic_dowload.svg';

  static const String ic_download_svg = 'assets/icons/ic_download.svg';

  static const String ic_edit_avatar_svg = 'assets/icons/ic_edit_avatar.svg';

  static const String ic_email_svg = 'assets/icons/ic_email.svg';

  static const String ic_filter_svg = 'assets/icons/ic_filter.svg';

  static const String ic_girl_onboard_svg = 'assets/icons/ic_girl_onboard.svg';

  static const String ic_google_pay_svg = 'assets/icons/ic_google_pay.svg';

  static const String ic_heart_svg = 'assets/icons/ic_heart.svg';

  static const String ic_helper_svg = 'assets/icons/ic_helper.svg';

  static const String ic_language_svg = 'assets/icons/ic_language.svg';

  static const String ic_logo_svg = 'assets/icons/ic_logo.svg';

  static const String ic_love_svg = 'assets/icons/ic_love.svg';

  static const String ic_my_list_svg = 'assets/icons/ic_my_list.svg';

  static const String ic_noti_svg = 'assets/icons/ic_noti.svg';

  static const String ic_notification_svg = 'assets/icons/ic_notification.svg';

  static const String ic_password_svg = 'assets/icons/ic_password.svg';

  static const String ic_paypal_svg = 'assets/icons/ic_paypal.svg';

  static const String ic_person_svg = 'assets/icons/ic_person.svg';

  static const String ic_play_svg = 'assets/icons/ic_play.svg';

  static const String ic_red_download_svg = 'assets/icons/ic_red_download.svg';

  static const String ic_scan_svg = 'assets/icons/ic_scan.svg';

  static const String ic_scanner_card_svg = 'assets/icons/ic_scanner_card.svg';

  static const String ic_search_svg = 'assets/icons/ic_search.svg';

  static const String ic_security_svg = 'assets/icons/ic_security.svg';

  static const String ic_send_svg = 'assets/icons/ic_send.svg';

  static const String ic_sercurity_svg = 'assets/icons/ic_sercurity.svg';

  static const String ic_share_svg = 'assets/icons/ic_share.svg';

  static const String ic_star_svg = 'assets/icons/ic_star.svg';

  static const String ic_tab_download_svg = 'assets/icons/ic_tab_download.svg';

  static const String ic_tab_explore_svg = 'assets/icons/ic_tab_explore.svg';

  static const String ic_tab_home_svg = 'assets/icons/ic_tab_home.svg';

  static const String ic_tab_my_list_svg = 'assets/icons/ic_tab_my_list.svg';

  static const String ic_tab_profile_svg = 'assets/icons/ic_tab_profile.svg';

  static const String ic_tab_selected_download_svg = 'assets/icons/ic_tab_selected_download.svg';

  static const String ic_tab_selected_explore_svg = 'assets/icons/ic_tab_selected_explore.svg';

  static const String ic_tab_selected_home_svg = 'assets/icons/ic_tab_selected_home.svg';

  static const String ic_tab_selected_my_list_svg = 'assets/icons/ic_tab_selected_my_list.svg';

  static const String ic_tab_selected_profile_svg = 'assets/icons/ic_tab_selected_profile.svg';

  static const String ic_unchecked_svg = 'assets/icons/ic_unchecked.svg';

  static const String avatar_default_jpg = 'assets/images/avatar_default.jpg';

  static const String bg_avatar_png = 'assets/images/bg_avatar.png';

  static const String bg_empty_png = 'assets/images/bg_empty.png';

  static const String bg_home_png = 'assets/images/bg_home.png';

  static const String bg_welcome_png = 'assets/images/bg_welcome.png';

  static const String empty_jpg = 'assets/images/empty.jpg';

  static const String video_unable_png = 'assets/images/video_unable.png';
}
